#Data path for data storage.
STOCK_DATA_ROOT = './StockData/'
REFERENCES_DATA_PATH = STOCK_DATA_ROOT + 'References/'
FUNDAMENTAL_DATA_PATH = STOCK_DATA_ROOT + 'Fundamental'
REPORTS_DATA_PATH = STOCK_DATA_ROOT + 'Reports/'
FAILED_LIST_PATH = STOCK_DATA_ROOT + 'Failed/'


DAILY_DATA_PAHT = STOCK_DATA_ROOT + 'Daily/'
RAW_DAILY_DATA_PATH = DAILY_DATA_PAHT + 'Raw/'
CLEAN_DAILY_DATA_PATH = DAILY_DATA_PAHT + 'Clean/'
UPDATE_DAILY_DATA_PATH = DAILY_DATA_PAHT + 'Update/'
WORK_DAILY_DATA_PATH = DAILY_DATA_PAHT + 'Work/'
TEMP_DAILY_DATA_PATH = DAILY_DATA_PAHT + 'Temp/'

MINUTE_DATA_PAHT = STOCK_DATA_ROOT + 'Minute/'
RAW_MINUTE_DATA_PATH = MINUTE_DATA_PAHT + 'Raw/'
CLEAN_MINUTE_DATA_PATH = MINUTE_DATA_PAHT + 'Clean/'
UPDATE_MINUTE_DATA_PATH = MINUTE_DATA_PAHT + 'Update/'
WORK_MINUTE_DATA_PATH = MINUTE_DATA_PAHT + 'Work/'
TEMP_MINUTE_DATA_PATH = MINUTE_DATA_PAHT + 'Temp/'

TESTING_DATA_PATH = STOCK_DATA_ROOT + 'Testing/'











 
